### ISSUE TITLE
err embedding batch

### ISSUE THREAD

**Issue by YouLe2016** [marcgreen/semantic-joplin#1]
[2022-03-08 22:57:59.765] [error] err embedding batch:  Error: Failed to link vertex and fragment shaders.
    at file:///D:/JoplinProfile/tmp/plugin_com.github.marcgreen.joplin-plugin-semantically-similar-notes.js:12314:6919
    at kw.createProgram (file:///D:/JoplinProfile/tmp/plugin_com.github.marcgreen.joplin-plugin-semantically-similar-notes.js:12314:6976)
    at file:///D:/JoplinProfile/tmp/plugin_com.github.marcgreen.joplin-plugin-semantically-similar-notes.js:12459:12921
    at file:///D:/JoplinProfile/tmp/plugin_com.github.marcgreen.joplin-plugin-semantically-similar-notes.js:12459:13916
    at Cx.getAndSaveBinary (file:///D:/JoplinProfile/tmp/plugin_com.github.marcgreen.joplin-plugin-semantically-similar-notes.js:12459:17151)
    at Cx.runWebGLProgram (file:///D:/JoplinProfile/tmp/plugin_com.github.marcgreen.joplin-plugin-semantically-similar-notes.js:12459:12380)
    at Cx.uploadToGPU (file:///D:/JoplinProfile/tmp/plugin_com.github.marcgreen.joplin-plugin-semantically-similar-notes.js:12459:19463)
    at file:///D:/JoplinProfile/tmp/plugin_com.github.marcgreen.joplin-plugin-semantically-similar-notes.js:12459:10836
    at Array.map (<anonymous>)
    at Cx.runWebGLProgram (file:///D:/JoplinProfile/tmp/plugin_com.github.marcgreen.joplin-plugin-semantically-similar-notes.js:12459:10373)
[2022-03-08 22:57:59.766] [info]  err embedding note, that's weird

![image](https://user-images.githubusercontent.com/23033537/157264976-90fa5447-1e63-4614-8bbd-29d05b43ffa1.png)

**Comment by marcgreen** [comment]
Thanks for opening this issue! I occasionally experience it myself too. It's at least sometimes accompanied by the UI going wonky for several seconds. A workaround is to restart joplin when this happens. 

The error message, stack trace, and graphical glitch all imply the issue is related to the gpu. Unfortunately that's as much as I know right now.

I also see a different error sometimes that also results in a graphical glitch for a moment and requires a restart, which might deserve its own Issue:
> 'Error: The new shape (NaN,0) has NaN elements and the old shape (0,0) has 0 elements. The new shape and old shape must have the same number of elements.'
